apiVersion: v1
kind: Service
metadata:
  name: quiz-topic-app-service
spec:
  selector:
    app: quiz-topic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # This will provision an external IP

